
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DECIMAL = 12;
  public static final int MENOS = 8;
  public static final int CORIZQ = 5;
  public static final int UMENOS = 13;
  public static final int ENTERO = 11;
  public static final int POR = 9;
  public static final int CORDER = 6;
  public static final int PTCOMA = 2;
  public static final int DIVIDIDO = 10;
  public static final int EOF = 0;
  public static final int MAS = 7;
  public static final int PARIZQ = 3;
  public static final int error = 1;
  public static final int PARDER = 4;
  public static final int REVALUAR = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PARIZQ",
  "PARDER",
  "CORIZQ",
  "CORDER",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "ENTERO",
  "DECIMAL",
  "UMENOS",
  "REVALUAR"
  };
}

