/* The following code was generated by JFlex 1.7.0 */



package Analizador;
import java_cup.runtime.Symbol; 


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>Lexico</tt>
 */
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\11\1\12\1\2\1\4\22\0\1\3\1\56\1\27"+
    "\2\0\1\60\1\61\1\26\1\43\1\44\1\13\1\47\1\0\1\50"+
    "\1\6\1\10\12\5\1\0\1\55\1\52\1\51\1\53\2\0\1\21"+
    "\1\42\1\40\1\41\1\17\1\20\1\7\1\37\1\33\2\7\1\22"+
    "\1\34\1\31\1\36\1\35\1\7\1\15\1\24\1\14\1\16\5\7"+
    "\1\0\1\30\1\0\1\54\1\25\1\0\1\21\1\42\1\40\1\41"+
    "\1\17\1\20\1\7\1\37\1\33\2\7\1\22\1\34\1\31\1\36"+
    "\1\35\1\7\1\15\1\24\1\14\1\16\5\7\1\45\1\57\1\46"+
    "\7\0\1\12\113\0\1\7\37\0\1\7\76\0\2\32\115\0\1\23"+
    "\u1ea8\0\1\12\1\12\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\3\4\1\1\1\4\1\1\1\10\1\1\7\4\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\1\1\25\1\1\1\26\1\27"+
    "\1\26\3\0\3\4\2\30\1\0\1\31\2\0\1\4"+
    "\1\0\7\4\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\2\1\0\3\4\1\0\1\4\1\31"+
    "\1\0\1\4\1\0\10\4\1\2\1\42\1\4\1\0"+
    "\2\43\1\0\1\4\1\0\6\4\1\0\3\4\1\42"+
    "\1\0\1\4\1\0\1\4\1\44\1\45\2\4\1\0"+
    "\1\4\1\0\2\4\1\46\1\0\1\4\1\0\2\4"+
    "\1\47\1\0\1\4\1\0\2\4\1\0\1\4\1\0"+
    "\2\4\1\0\1\4\2\50\1\4\2\51\2\52\1\53"+
    "\1\0\1\4\1\54\2\55";

  private static int [] zzUnpackAction() {
    int [] result = new int[155];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\144\0\226\0\310\0\372\0\144"+
    "\0\144\0\u012c\0\u015e\0\u0190\0\u01c2\0\u01f4\0\u0226\0\144"+
    "\0\u0258\0\u028a\0\u02bc\0\u02ee\0\u0320\0\u0352\0\u0384\0\u03b6"+
    "\0\144\0\144\0\144\0\144\0\144\0\144\0\144\0\144"+
    "\0\144\0\144\0\144\0\144\0\u03e8\0\144\0\u041a\0\144"+
    "\0\144\0\u044c\0\u047e\0\u04b0\0\u04e2\0\u0514\0\u0546\0\u0578"+
    "\0\u05aa\0\u05dc\0\u060e\0\144\0\u0640\0\u0672\0\u06a4\0\u06d6"+
    "\0\u0708\0\u073a\0\u076c\0\u079e\0\u07d0\0\u0802\0\u0834\0\144"+
    "\0\144\0\144\0\144\0\144\0\144\0\144\0\u047e\0\u0866"+
    "\0\u0898\0\u08ca\0\u08fc\0\u092e\0\u0960\0\u0992\0\u060e\0\u09c4"+
    "\0\u09f6\0\u0a28\0\u0a5a\0\u0a8c\0\u0abe\0\u0af0\0\u0b22\0\u0b54"+
    "\0\u0b86\0\u0bb8\0\u04e2\0\310\0\u0bea\0\u0c1c\0\144\0\310"+
    "\0\u0c4e\0\u0c80\0\u0cb2\0\u0ce4\0\u0d16\0\u0d48\0\u0d7a\0\u0dac"+
    "\0\u0dde\0\u0e10\0\u0e42\0\u0e74\0\u0ea6\0\144\0\u0ed8\0\u0f0a"+
    "\0\u0f3c\0\u0f6e\0\310\0\310\0\u0fa0\0\u0fd2\0\u1004\0\u1036"+
    "\0\u1068\0\u109a\0\u10cc\0\310\0\u10fe\0\u1130\0\u1162\0\u1194"+
    "\0\u11c6\0\310\0\u11f8\0\u122a\0\u125c\0\u128e\0\u12c0\0\u12f2"+
    "\0\u1324\0\u1356\0\u1388\0\u13ba\0\u13ec\0\u141e\0\144\0\310"+
    "\0\u1450\0\144\0\310\0\144\0\310\0\310\0\u1482\0\u14b4"+
    "\0\310\0\144\0\310";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[155];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\4\4\1\5\1\3\1\6\1\7\1\10\1\0"+
    "\1\11\1\12\2\6\1\13\1\14\2\6\1\15\1\16"+
    "\1\3\1\17\1\20\1\3\1\6\1\21\1\22\1\23"+
    "\1\24\1\6\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\2\50\1\0\1\50"+
    "\1\0\4\50\2\0\14\50\1\51\1\52\31\50\67\0"+
    "\1\5\1\53\60\0\1\6\1\0\1\6\4\0\7\6"+
    "\1\0\2\6\3\0\1\6\1\0\10\6\27\0\1\54"+
    "\2\0\1\55\53\0\1\6\1\0\1\6\4\0\1\6"+
    "\1\56\5\6\1\0\2\6\3\0\1\6\1\0\10\6"+
    "\24\0\1\6\1\0\1\6\4\0\7\6\1\0\2\6"+
    "\3\0\1\57\1\0\10\6\24\0\1\6\1\0\1\6"+
    "\4\0\5\6\1\60\1\6\1\0\2\6\3\0\1\6"+
    "\1\0\10\6\51\0\2\61\33\0\1\6\1\0\1\6"+
    "\4\0\7\6\1\0\2\6\3\0\1\6\1\61\1\62"+
    "\7\6\17\0\1\63\1\0\7\63\1\0\14\63\1\64"+
    "\1\0\1\65\31\63\34\0\1\66\32\0\1\6\1\0"+
    "\1\6\4\0\7\6\1\0\2\6\3\0\1\6\1\0"+
    "\1\6\1\67\6\6\24\0\1\6\1\0\1\6\4\0"+
    "\7\6\1\0\2\6\3\0\1\6\1\70\1\71\7\6"+
    "\24\0\1\6\1\0\1\6\4\0\5\6\1\72\1\6"+
    "\1\0\2\6\3\0\1\6\1\0\10\6\24\0\1\6"+
    "\1\0\1\6\4\0\5\6\1\73\1\6\1\0\2\6"+
    "\3\0\1\6\1\0\10\6\24\0\1\6\1\0\1\6"+
    "\4\0\5\6\1\74\1\6\1\0\2\6\3\0\1\6"+
    "\1\0\3\6\1\75\4\6\24\0\1\6\1\0\1\6"+
    "\4\0\3\6\1\76\3\6\1\0\2\6\3\0\1\6"+
    "\1\0\10\6\24\0\1\6\1\0\1\6\4\0\7\6"+
    "\1\0\2\6\3\0\1\6\1\0\3\6\1\77\4\6"+
    "\76\0\1\100\63\0\1\101\14\0\1\102\1\103\11\0"+
    "\1\104\1\105\1\106\35\0\1\107\54\0\2\54\1\0"+
    "\1\54\1\110\4\54\1\4\1\0\47\54\2\55\1\0"+
    "\7\55\1\0\1\111\46\55\5\0\1\6\1\0\1\6"+
    "\4\0\2\6\1\112\4\6\1\0\2\6\3\0\1\6"+
    "\1\0\10\6\24\0\1\6\1\0\1\6\4\0\1\113"+
    "\6\6\1\0\2\6\3\0\1\6\1\0\10\6\24\0"+
    "\1\6\1\0\1\6\4\0\6\6\1\114\1\0\2\6"+
    "\3\0\1\6\1\0\10\6\50\0\1\115\35\0\1\6"+
    "\1\0\1\6\4\0\7\6\1\0\2\6\3\0\1\116"+
    "\1\0\10\6\45\0\1\64\47\0\1\63\11\0\1\117"+
    "\1\63\1\0\1\63\65\0\1\120\31\0\1\6\1\0"+
    "\1\6\4\0\7\6\1\0\2\6\3\0\1\6\1\0"+
    "\2\6\1\121\5\6\36\0\1\122\47\0\1\6\1\0"+
    "\1\6\4\0\3\6\1\123\3\6\1\0\2\6\3\0"+
    "\1\6\1\0\10\6\24\0\1\6\1\0\1\6\4\0"+
    "\1\6\1\124\5\6\1\0\2\6\3\0\1\6\1\0"+
    "\10\6\24\0\1\6\1\0\1\6\4\0\7\6\1\0"+
    "\2\6\3\0\1\6\1\0\5\6\1\125\2\6\24\0"+
    "\1\6\1\0\1\6\4\0\1\6\1\126\5\6\1\0"+
    "\2\6\3\0\1\6\1\0\6\6\1\127\1\6\24\0"+
    "\1\6\1\0\1\6\4\0\7\6\1\0\2\6\3\0"+
    "\1\130\1\0\10\6\24\0\1\6\1\0\1\6\4\0"+
    "\7\6\1\0\2\6\3\0\1\6\1\0\5\6\1\131"+
    "\2\6\24\0\1\6\1\0\1\6\4\0\7\6\1\0"+
    "\2\6\3\0\1\6\1\0\3\6\1\132\4\6\30\0"+
    "\1\4\50\0\2\55\1\0\5\55\1\133\1\55\1\0"+
    "\1\111\46\55\5\0\1\6\1\0\1\6\4\0\3\6"+
    "\1\134\3\6\1\0\2\6\3\0\1\6\1\0\10\6"+
    "\24\0\1\6\1\0\1\6\4\0\3\6\1\135\3\6"+
    "\1\0\2\6\3\0\1\6\1\0\10\6\24\0\1\6"+
    "\1\0\1\6\4\0\7\6\1\136\1\112\1\6\3\0"+
    "\1\6\1\0\10\6\55\0\1\137\30\0\1\6\1\0"+
    "\1\6\4\0\7\6\1\0\2\6\3\0\1\6\1\0"+
    "\3\6\1\140\4\6\34\0\1\141\51\0\1\6\1\0"+
    "\1\6\4\0\1\6\1\142\5\6\1\0\2\6\3\0"+
    "\1\6\1\0\10\6\50\0\1\143\35\0\1\6\1\0"+
    "\1\6\4\0\7\6\1\0\2\6\3\0\1\144\1\0"+
    "\10\6\24\0\1\6\1\0\1\6\4\0\5\6\1\145"+
    "\1\6\1\0\2\6\3\0\1\6\1\0\10\6\24\0"+
    "\1\6\1\0\1\6\4\0\3\6\1\146\3\6\1\0"+
    "\2\6\3\0\1\6\1\0\10\6\24\0\1\6\1\0"+
    "\1\6\4\0\5\6\1\147\1\6\1\0\2\6\3\0"+
    "\1\6\1\0\10\6\24\0\1\6\1\0\1\6\4\0"+
    "\3\6\1\150\3\6\1\0\2\6\3\0\1\6\1\0"+
    "\10\6\24\0\1\6\1\0\1\6\4\0\1\151\6\6"+
    "\1\0\2\6\3\0\1\6\1\0\10\6\24\0\1\6"+
    "\1\0\1\6\4\0\7\6\1\0\2\6\3\0\1\6"+
    "\1\152\1\153\7\6\24\0\1\6\1\0\1\6\4\0"+
    "\6\6\1\154\1\0\2\6\3\0\1\6\1\0\10\6"+
    "\24\0\1\6\1\0\1\6\4\0\1\6\1\155\5\6"+
    "\1\0\2\6\3\0\1\6\1\0\10\6\36\0\1\156"+
    "\74\0\2\157\33\0\1\6\1\0\1\6\4\0\7\6"+
    "\1\0\2\6\3\0\1\6\1\157\1\160\7\6\33\0"+
    "\1\161\52\0\1\6\1\0\1\6\4\0\1\162\6\6"+
    "\1\0\2\6\3\0\1\6\1\0\10\6\24\0\1\6"+
    "\1\0\1\6\4\0\1\6\1\163\5\6\1\0\2\6"+
    "\3\0\1\6\1\0\10\6\24\0\1\6\1\0\1\6"+
    "\4\0\1\6\1\164\5\6\1\0\2\6\3\0\1\6"+
    "\1\0\10\6\24\0\1\6\1\0\1\6\4\0\7\6"+
    "\1\0\2\6\3\0\1\6\1\0\5\6\1\165\2\6"+
    "\24\0\1\6\1\0\1\6\4\0\7\6\1\0\2\6"+
    "\3\0\1\166\1\0\10\6\24\0\1\6\1\0\1\6"+
    "\4\0\7\6\1\0\2\6\3\0\1\6\1\167\1\170"+
    "\7\6\53\0\1\171\32\0\1\6\1\0\1\6\4\0"+
    "\7\6\1\0\2\6\3\0\1\6\1\0\1\6\1\172"+
    "\6\6\24\0\1\6\1\0\1\6\4\0\3\6\1\173"+
    "\3\6\1\0\2\6\3\0\1\6\1\0\10\6\24\0"+
    "\1\6\1\0\1\6\4\0\7\6\1\0\2\6\3\0"+
    "\1\6\1\0\3\6\1\174\4\6\53\0\1\175\32\0"+
    "\1\6\1\0\1\6\4\0\7\6\1\0\2\6\3\0"+
    "\1\6\1\0\1\6\1\176\6\6\34\0\1\177\51\0"+
    "\1\6\1\0\1\6\4\0\1\6\1\200\5\6\1\0"+
    "\2\6\3\0\1\6\1\0\10\6\24\0\1\6\1\0"+
    "\1\6\4\0\1\201\6\6\1\0\2\6\3\0\1\6"+
    "\1\0\10\6\24\0\1\6\1\0\1\6\4\0\5\6"+
    "\1\202\1\6\1\0\2\6\3\0\1\6\1\0\10\6"+
    "\50\0\1\203\35\0\1\6\1\0\1\6\4\0\7\6"+
    "\1\0\2\6\3\0\1\204\1\0\10\6\40\0\1\205"+
    "\45\0\1\6\1\0\1\6\4\0\5\6\1\206\1\6"+
    "\1\0\2\6\3\0\1\6\1\0\10\6\24\0\1\6"+
    "\1\0\1\6\4\0\5\6\1\207\1\6\1\0\2\6"+
    "\3\0\1\6\1\0\10\6\51\0\2\210\33\0\1\6"+
    "\1\0\1\6\4\0\7\6\1\0\2\6\3\0\1\6"+
    "\1\210\1\211\7\6\40\0\1\212\45\0\1\6\1\0"+
    "\1\6\4\0\5\6\1\213\1\6\1\0\2\6\3\0"+
    "\1\6\1\0\10\6\24\0\1\6\1\0\1\6\4\0"+
    "\3\6\1\214\3\6\1\0\2\6\3\0\1\6\1\0"+
    "\10\6\35\0\1\215\50\0\1\6\1\0\1\6\4\0"+
    "\2\6\1\216\4\6\1\0\2\6\3\0\1\6\1\0"+
    "\10\6\41\0\1\217\44\0\1\6\1\0\1\6\4\0"+
    "\6\6\1\220\1\0\2\6\3\0\1\6\1\0\10\6"+
    "\24\0\1\6\1\0\1\6\4\0\7\6\1\0\2\6"+
    "\3\0\1\221\1\0\10\6\34\0\1\222\51\0\1\6"+
    "\1\0\1\6\4\0\1\6\1\223\5\6\1\0\2\6"+
    "\3\0\1\6\1\0\10\6\42\0\2\224\42\0\1\6"+
    "\1\0\1\6\4\0\7\6\1\224\1\225\1\6\3\0"+
    "\1\6\1\0\10\6\24\0\1\6\1\0\1\6\4\0"+
    "\1\6\1\226\5\6\1\0\2\6\3\0\1\6\1\0"+
    "\10\6\40\0\1\227\45\0\1\6\1\0\1\6\4\0"+
    "\5\6\1\230\1\6\1\0\2\6\3\0\1\6\1\0"+
    "\10\6\24\0\1\6\1\0\1\6\4\0\7\6\1\0"+
    "\2\6\3\0\1\6\1\0\3\6\1\231\4\6\34\0"+
    "\1\232\51\0\1\6\1\0\1\6\4\0\1\6\1\233"+
    "\5\6\1\0\2\6\3\0\1\6\1\0\10\6\17\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5350];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\3\1\2\11\6\1\1\11\10\1\14\11"+
    "\1\1\1\11\1\1\2\11\1\1\3\0\5\1\1\0"+
    "\1\11\2\0\1\1\1\0\7\1\7\11\2\1\1\0"+
    "\3\1\1\0\2\1\1\0\1\1\1\0\13\1\1\0"+
    "\1\11\1\1\1\0\1\1\1\0\6\1\1\0\3\1"+
    "\1\11\1\0\1\1\1\0\5\1\1\0\1\1\1\0"+
    "\3\1\1\0\1\1\1\0\3\1\1\0\1\1\1\0"+
    "\2\1\1\0\1\1\1\0\2\1\1\0\1\1\1\11"+
    "\2\1\1\11\1\1\1\11\2\1\1\0\2\1\1\11"+
    "\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[155];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    StringBuffer NuevoString = new StringBuffer();
    StringBuffer NuevoIdentificador = new StringBuffer(); 


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
      
    yyline = 1; 
    yychar = 1; 
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 220) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Este es un error lexico: "+yytext()+", en la linea: "+yyline+", en la columna: "+yychar);
            } 
            // fall through
          case 46: break;
          case 2: 
            { 
            } 
            // fall through
          case 47: break;
          case 3: 
            { return new Symbol(sym.ENTERO,yyline,yychar, yytext());
            } 
            // fall through
          case 48: break;
          case 4: 
            { return new Symbol(sym.IDENTIFICADOR,yyline,yychar,yytext());
            } 
            // fall through
          case 49: break;
          case 5: 
            { return new Symbol(sym.DIV,yyline,yychar, yytext());
            } 
            // fall through
          case 50: break;
          case 6: 
            { yychar=1;
            } 
            // fall through
          case 51: break;
          case 7: 
            { return new Symbol(sym.POR,yyline,yychar, yytext());
            } 
            // fall through
          case 52: break;
          case 8: 
            { yybegin(STRING); NuevoString.setLength(0);
            } 
            // fall through
          case 53: break;
          case 9: 
            { return new Symbol(sym.PARA,yyline,yychar, yytext());
            } 
            // fall through
          case 54: break;
          case 10: 
            { return new Symbol(sym.PARC,yyline,yychar, yytext());
            } 
            // fall through
          case 55: break;
          case 11: 
            { return new Symbol(sym.LLAVEA,yyline,yychar, yytext());
            } 
            // fall through
          case 56: break;
          case 12: 
            { return new Symbol(sym.LLAVEC,yyline,yychar, yytext());
            } 
            // fall through
          case 57: break;
          case 13: 
            { return new Symbol(sym.MAS,yyline,yychar, yytext());
            } 
            // fall through
          case 58: break;
          case 14: 
            { return new Symbol(sym.MENOS,yyline,yychar, yytext());
            } 
            // fall through
          case 59: break;
          case 15: 
            { return new Symbol(sym.IGUAL,yyline,yychar, yytext());
            } 
            // fall through
          case 60: break;
          case 16: 
            { return new Symbol(sym.MENORQUE,yyline,yychar, yytext());
            } 
            // fall through
          case 61: break;
          case 17: 
            { return new Symbol(sym.MAYORQUE,yyline,yychar, yytext());
            } 
            // fall through
          case 62: break;
          case 18: 
            { return new Symbol(sym.POT,yyline,yychar, yytext());
            } 
            // fall through
          case 63: break;
          case 19: 
            { return new Symbol(sym.PUNTOYCOMA,yyline,yychar, yytext());
            } 
            // fall through
          case 64: break;
          case 20: 
            { return new Symbol(sym.NOT,yyline,yychar, yytext());
            } 
            // fall through
          case 65: break;
          case 21: 
            { return new Symbol(sym.MOD,yyline,yychar, yytext());
            } 
            // fall through
          case 66: break;
          case 22: 
            { NuevoString.append(yytext());
            } 
            // fall through
          case 67: break;
          case 23: 
            { yybegin(YYINITIAL); return new Symbol(sym.CADENA,yyline,yychar,NuevoString.toString());
            } 
            // fall through
          case 68: break;
          case 24: 
            { return new Symbol(sym.RIF,yyline,yychar, yytext());
            } 
            // fall through
          case 69: break;
          case 25: 
            { return new Symbol(sym.CARACTER,yyline,yychar, yytext().replace("'",""));
            } 
            // fall through
          case 70: break;
          case 26: 
            { return new Symbol(sym.OR,yyline,yychar, yytext());
            } 
            // fall through
          case 71: break;
          case 27: 
            { return new Symbol(sym.AND,yyline,yychar, yytext());
            } 
            // fall through
          case 72: break;
          case 28: 
            { NuevoString.append('\t');
            } 
            // fall through
          case 73: break;
          case 29: 
            { NuevoString.append('\r');
            } 
            // fall through
          case 74: break;
          case 30: 
            { NuevoString.append('\"');
            } 
            // fall through
          case 75: break;
          case 31: 
            { NuevoString.append("\\");
            } 
            // fall through
          case 76: break;
          case 32: 
            { NuevoString.append('\n');
            } 
            // fall through
          case 77: break;
          case 33: 
            { return new Symbol(sym.DECIMAL,yyline,yychar, yytext());
            } 
            // fall through
          case 78: break;
          case 34: 
            { return new Symbol(sym.BOOLEANO,yyline,yychar, yytext());
            } 
            // fall through
          case 79: break;
          case 35: 
            { return new Symbol(sym.RELSE,yyline,yychar, yytext());
            } 
            // fall through
          case 80: break;
          case 36: 
            { return new Symbol(sym.RBREAK,yyline,yychar, yytext());
            } 
            // fall through
          case 81: break;
          case 37: 
            { return new Symbol(sym.RDO,yyline,yychar, yytext());
            } 
            // fall through
          case 82: break;
          case 38: 
            { return new Symbol(sym.RENTERO,yyline,yychar, yytext());
            } 
            // fall through
          case 83: break;
          case 39: 
            { return new Symbol(sym.RCADENA,yyline,yychar, yytext());
            } 
            // fall through
          case 84: break;
          case 40: 
            { return new Symbol(sym.RDECIMAL,yyline,yychar, yytext());
            } 
            // fall through
          case 85: break;
          case 41: 
            { return new Symbol(sym.RPRINT,yyline,yychar, yytext());
            } 
            // fall through
          case 86: break;
          case 42: 
            { return new Symbol(sym.RWHILE,yyline,yychar, yytext());
            } 
            // fall through
          case 87: break;
          case 43: 
            { return new Symbol(sym.RCARACTER,yyline,yychar, yytext());
            } 
            // fall through
          case 88: break;
          case 44: 
            { return new Symbol(sym.RBOOLEANO,yyline,yychar, yytext());
            } 
            // fall through
          case 89: break;
          case 45: 
            { return new Symbol(sym.RCONTINUE,yyline,yychar, yytext());
            } 
            // fall through
          case 90: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
