
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 18;
  public static final int AND = 22;
  public static final int MENOS = 14;
  public static final int PUNTOYCOMA = 25;
  public static final int CADENA = 3;
  public static final int OR = 23;
  public static final int IGUAL = 19;
  public static final int DECIMAL = 5;
  public static final int NOT = 24;
  public static final int MAYORQUE = 21;
  public static final int UMENOS = 26;
  public static final int POT = 17;
  public static final int PARC = 12;
  public static final int LLAVEC = 10;
  public static final int PARA = 11;
  public static final int LLAVEA = 9;
  public static final int POR = 15;
  public static final int BOOLEANO = 6;
  public static final int CARACTER = 7;
  public static final int EOF = 0;
  public static final int MENORQUE = 20;
  public static final int RPRINT = 8;
  public static final int DIV = 16;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 2;
  public static final int ENTERO = 4;
  public static final int MAS = 13;
  public static final int DIF = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFICADOR",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "BOOLEANO",
  "CARACTER",
  "RPRINT",
  "LLAVEA",
  "LLAVEC",
  "PARA",
  "PARC",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "POT",
  "MOD",
  "IGUAL",
  "MENORQUE",
  "MAYORQUE",
  "AND",
  "OR",
  "NOT",
  "PUNTOYCOMA",
  "UMENOS",
  "DIF"
  };
}

